# Note: fastapi is a web framework for python
# it supports async def endpoints
# It is built on top of
# Starlette → Handles the web server parts (requests, responses, routing, middleware).
# Pydantic → Handles data validation, parsing, and serialization.
from fastapi import FastAPI, Request
from fastapi.middleware.cors import CORSMiddleware
from fastapi.middleware.gzip import GZipMiddleware
from fastapi.responses import JSONResponse
from app.api.v1 import api_router
from app.core.config import settings


# here we initialize fastapi app]
# this metadata shows up in the fastapi docs page, which is autogenerated and can be accessed at /docs or /redoc
app = FastAPI(
    title="World Map Intelligence API",
    description="AI-powered country intelligence and analytics",
    version="1.0.0",
    docs_url="/docs",
    redoc_url="/redoc",
)

# CORS - Allow everything for now
# middleware is a layer between client requests and your api endpoints
# If your frontend (React, Vue, Angular, etc.) 
# is hosted on a different domain than your FastAPI backend, 
# the browser will block API calls unless you enable CORS on the backend.'''

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # allows requests from any domain, restrict in production
    allow_credentials=False, # if true would allow cookies
    allow_methods=["*"], # Allows all HTTP methods GET, POST, etc.., restrict in production
    allow_headers=["*"], # Restrict in production
)

# This compresses responses larger than 1000 bytes using GZip.
# Makes network traffic lighter → frontend loads faster
app.add_middleware(GZipMiddleware, minimum_size=1000)

# Manual CORS handling for extra safety
# Ensures CORS handles OPTIONS
@app.middleware("http")
async def cors_middleware(request: Request, call_next):
    # Handle preflight requests
    if request.method == "OPTIONS":
        response = JSONResponse(content="OK")
        response.headers["Access-Control-Allow-Origin"] = "*"
        response.headers["Access-Control-Allow-Methods"] = "GET, POST, PUT, DELETE, OPTIONS"
        response.headers["Access-Control-Allow-Headers"] = "*"
        return response
    
    # Process the request
    response = await call_next(request)
    
    # Add CORS headers to all responses
    response.headers["Access-Control-Allow-Origin"] = "*"
    response.headers["Access-Control-Allow-Methods"] = "GET, POST, PUT, DELETE, OPTIONS"
    response.headers["Access-Control-Allow-Headers"] = "*"
    
    return response

# Include API routes, pulls all routes defined in api_router inside app/api/v1
app.include_router(api_router, prefix="/api/v1")

# simple landing endpoint
@app.get("/")
async def root():
    return {"message": "World Map Intelligence API", "version": "1.0.0"}

# quick check to confirm backend is alive & CORS is working
@app.get("/health")
async def health_check():
    return {"status": "healthy", "cors": "enabled"}

# useful for the frontend to test connectivity to the backend API
@app.get("/api/v1/ping")
async def ping():
    return {
        "message": "Backend is connected!",
        "status": "success",
        "cors": "working"
    }

